### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by qibinghua** [MVDB0110/OC-XPS13-7390#2]
What is bois setting?

**Comment by MVDB0110** [comment]
> What is bois setting?

Hi qibinghua,

What is your specific error when trying to boot from your USB.

**Comment by MVDB0110** [comment]
@qibinghua I have updated my README to have essential bios settings displayed. If you still run into errors I will need more information about the error.

**Comment by MVDB0110** [comment]
No active participant.
